"""
Safety checks for SQL generated by the DB AI Agent.

Important:
The real protection is the read-only PostgreSQL user.
This file adds an extra application-level validation layer.
"""

import re

from agent.config import ALLOWED_SCHEMA


BLOCKED_KEYWORDS = [
    "insert",
    "update",
    "delete",
    "drop",
    "alter",
    "truncate",
    "create",
    "grant",
    "revoke",
    "call",
    "copy",
]


def clean_sql_response(response_text: str) -> str:
    """
    Remove markdown formatting from SQL generated by the model.
    """

    cleaned = response_text.strip()
    cleaned = cleaned.replace("```sql", "")
    cleaned = cleaned.replace("```", "")
    cleaned = cleaned.strip()

    return cleaned


def is_safe_select_query(sql_query: str) -> bool:
    """
    Validate that the SQL query is safe enough to execute.

    Rules:
    - Must start with SELECT
    - Must query the allowed schema
    - Must not contain dangerous SQL keywords
    - Must not contain multiple SQL statements
    """

    normalized_sql = sql_query.lower().strip()

    # Remove one final semicolon if present.
    if normalized_sql.endswith(";"):
        normalized_sql = normalized_sql[:-1].strip()

    # Block multiple statements.
    if ";" in normalized_sql:
        return False

    if not normalized_sql.startswith("select"):
        return False

    if f"{ALLOWED_SCHEMA}." not in normalized_sql:
        return False

    for keyword in BLOCKED_KEYWORDS:
        pattern = rf"\b{keyword}\b"
        if re.search(pattern, normalized_sql):
            return False

    return True