"""
Safety checks for SQL generated by the DB AI Assistant.

Important:
The real protection is the read-only database user.
This file adds an extra application-level validation layer.
"""

import re

from agent.config import ALLOWED_SCHEMA


BLOCKED_KEYWORDS = [
    "insert",
    "update",
    "delete",
    "drop",
    "alter",
    "truncate",
    "create",
    "grant",
    "revoke",
    "call",
    "copy",
    "merge",
    "execute",
    "exec",
    "declare",
    "begin",
    "commit",
    "rollback",
    "dbcc",
]


def clean_sql_response(response_text: str) -> str:
    """
    Remove markdown formatting from SQL generated by the model.
    """

    cleaned = response_text.strip()
    cleaned = cleaned.replace("```sql", "")
    cleaned = cleaned.replace("```", "")
    cleaned = cleaned.strip()

    return cleaned


def remove_sql_comments(sql_query: str) -> str:
    """
    Remove simple SQL comments before validation.
    """

    without_line_comments = re.sub(
        r"--.*?$",
        "",
        sql_query,
        flags=re.MULTILINE,
    )

    without_block_comments = re.sub(
        r"/\*.*?\*/",
        "",
        without_line_comments,
        flags=re.DOTALL,
    )

    return without_block_comments


def normalize_sql_for_validation(sql_query: str) -> str:
    """
    Normalize SQL text for simple safety validation.
    """

    no_comments_sql = remove_sql_comments(sql_query)

    normalized_sql = no_comments_sql.lower().strip()

    # Remove one final semicolon if present.
    if normalized_sql.endswith(";"):
        normalized_sql = normalized_sql[:-1].strip()

    # Normalize common identifier quoting styles.
    normalized_sql = normalized_sql.replace("[", "")
    normalized_sql = normalized_sql.replace("]", "")
    normalized_sql = normalized_sql.replace('"', "")

    return normalized_sql


def is_safe_select_query(sql_query: str) -> bool:
    """
    Validate that the SQL query is safe enough to execute.

    Rules:
    - Must start with SELECT
    - Must query the allowed schema when a schema is configured
    - Must not contain dangerous SQL keywords
    - Must not contain multiple SQL statements
    """

    normalized_sql = normalize_sql_for_validation(sql_query)

    # Block multiple statements.
    if ";" in normalized_sql:
        return False

    if not normalized_sql.startswith("select"):
        return False

    if ALLOWED_SCHEMA:
        allowed_schema = ALLOWED_SCHEMA.lower().strip()

        if f"{allowed_schema}." not in normalized_sql:
            return False

    for keyword in BLOCKED_KEYWORDS:
        pattern = rf"\b{keyword}\b"

        if re.search(pattern, normalized_sql):
            return False

    # SQL Server extended procedures are dangerous.
    if "xp_" in normalized_sql:
        return False

    return True